[project]
name = "assetmanagement"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.15",
    "numpy>=2.3.3",
    "pandas>=2.3.2",
    "pybithumb>=1.0.21",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
]
